from langchain_community.vectorstores import FAISS
from app.embeddings.provider import OllamaEmbeddings

def retrieve(question, settings):
    if not (settings.faiss_persist_dir / "index.faiss").exists():
        raise FileNotFoundError("Falta el indice FAISS. Ejecuta python scripts/ingest.py.")
    # Load only the local index generated by this project's ingestion.
    store = FAISS.load_local(
        str(settings.faiss_persist_dir), OllamaEmbeddings(settings),
        allow_dangerous_deserialization=True,
    )
    return store.similarity_search_with_score(question, k=settings.top_k)
